site_name: APRStoSQL Wiki
site_url: https://n8acl.github.io/aprstosql
repo_url: https://github.com/n8acl/aprstosql
theme:
  name: 'material'
  font:
    text: 'Ubuntu'
    code: 'Ubuntu Mono'
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: light
      primary: 'amber'
      accent: 'orange'
      toggle:
        icon: material/toggle-switch-off-outline
        name: Embrace the dark side
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: 'deep orange'
      accent: 'amber'
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

markdown_extensions:
  - admonition
  - def_list
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true

nav:
  - Welcome!: index.md
  - About APRStoSQL: about.md
  - Installation/Setup: 
    - Configuration Setting Guide: configuration_guide.md
    - Standalone Application: installation_standalone.md
    - Running in Docker: installation_docker.md
  - Database: 
    - Description: database_description.md
    - Helpful Queries: database_queries.md
    - Data Management: database_datamanagement.md
  
  - Change Log: changelog.md

